server:
  port: 8080
  
spring:
  application:
    name: demo

management:
  port: 8080
  context-path: /monitoring
      
zuul:
  routes:
    fiche:
      path: /api/fiche/unite-physiques/**
      url: http://localhost:8090/api/fiche-descriptive/unite-physiques
    dispo:
      path: /api/dispo/**
      url: https://darwin-dev1.intra.sepaq.com/dispo-connector/api/disponibilite/